### ISSUE TITLE
Add ingame command

### ISSUE THREAD

**Issue by genuine96** [Hexer10/HexTags#72] opened 2020-06-20 11:12 UTC
add ingame command to add tag and colors. Ex:

**sm_addscoretag
sm_addchattag
sm_addchatcolor
sm_addnamecolor**

Im giving custom tags and it is really annoying to edit cfg every time

**Comment by Hexer10** [comment] 2020-08-05 09:21
Dupe of #49

**Closed by Hexer10** 2020-08-05 09:21 UTC
