### ISSUE TITLE
Create an unequip function.

### ISSUE THREAD

**Issue by Leon7810** [Hexer10/HexTags#45] opened 2020-01-03 14:30 UTC
**Is your feature request related to a problem? Please describe.**
It would be useful if there would be an unequip command. Like /removetag or /unequip.
As it currently forces players to wear it.

**Describe the solution you'd like**
That there would be an unequip function as it just would be helpful.

**Describe alternatives you've considered**
None.

**System Details**
 - OS: [e.g. Ubuntu] Windows
 - Game [e.g. CSGO] CSGO
 - Sourcemod version (send `sm version` reply from *server* console.) Latest

**Comment by Leon7810** [comment] 2020-01-03 14:32
I just noticed that there already is a request for this.
https://github.com/Hexer10/HexTags/issues/14

**Comment by Hexer10** [comment] 2020-01-03 16:35
Indeed dupe of #14

**Closed** 2020-01-03 16:35 UTC

**Comment by LionKing78** [comment] 2020-01-03 17:00
Yeah but it hasn’t been added yet.
